// 3_service_templates/quant_vite_base/src/App.svelte
<script>
    import { onMount } from 'svelte';
    import { fabric } from '../../_shared/utils/fabric-client.ts';

    // Props from Fabric Loader
    let { app_slug = "{{APP_SLUG}}" } = $props();
    const APP_NAME = "{{APP_NAME}}";

    // --- State ---
    let prices = $state([]);
    let status = $state("Node Active");
    let lastSignal = $state(null);
    
    // Aggregated Dashboard State
    let activeStrategies = $state({});
    
    // Derived total value using Svelte 5 runes
    let totalPortfolioValue = $derived(
        Object.values(activeStrategies).reduce((sum, strat) => sum + strat.value, 0)
    );

    onMount(() => {
        // 1. Subscribe to local shard updates
        fabric.onEvent("price_update", (data) => {
            prices = [...prices, data].slice(-20);
        });

        fabric.onEvent("signal_alert", (data) => {
            if(data.slug === app_slug) lastSignal = data.msg;
        });

        // 2. Subscribe to Global Portfolio Updates
        // This catches ticks from ANY quant shard in the system
        const unsubscribe = fabric.onEvent("portfolio_pnl_update", (data) => {
            activeStrategies[data.slug] = {
                value: data.total_value,
                pnl: data.daily_pnl_perc,
                lastUpdated: new Date(data.timestamp * 1000).toLocaleTimeString()
            };
        });

        return () => unsubscribe();
    });

    async function triggerBacktest() {
        status = "Processing Engine...";
        const res = await fetch(`/app/core/${app_slug}/api/backtest-results`);
        status = "Pipeline Complete";
    }
</script>

<main class="quant-terminal p-6 bg-slate-950 text-slate-300 min-h-screen font-sans">
    <header class="mb-8 border-b border-white/10 pb-6 flex justify-between items-end">
        <div>
            <h1 class="text-3xl font-black text-white uppercase tracking-tighter">{{APP_NAME}}</h1>
            <p class="text-xs text-slate-500 uppercase tracking-widest mt-1">Fabric Terminal Hub</p>
        </div>
        <div class="text-right">
            <span class="text-[10px] font-black text-slate-500 uppercase block mb-1">Total Net Liquidity</span>
            <span class="text-4xl font-black text-indigo-500 font-mono">
                ${totalPortfolioValue.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </span>
        </div>
    </header>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Dashboard: Strategy List -->
        <section class="lg:col-span-2 card bg-slate-900/50 p-6 rounded-2xl border border-white/5">
            <h2 class="text-[10px] font-black uppercase text-slate-500 tracking-[0.2em] mb-6">Active Data Streams</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                {#each Object.entries(activeStrategies) as [slug, strat]}
                    <div class="bg-slate-950/50 border border-white/5 p-4 rounded-xl flex justify-between items-center group hover:border-indigo-500/30 transition-all">
                        <div>
                            <h3 class="font-bold text-sm text-indigo-400 uppercase">{slug}</h3>
                            <p class="text-[9px] text-slate-600">Tick: {strat.lastUpdated}</p>
                        </div>
                        <div class="text-right">
                            <p class="text-base font-bold text-white">${strat.value.toLocaleString()}</p>
                            <p class="text-[10px] font-mono {strat.pnl >= 0 ? 'text-emerald-500' : 'text-rose-500'}">
                                {strat.pnl >= 0 ? '▲' : '▼'} {Math.abs(strat.pnl)}%
                            </p>
                        </div>
                    </div>
                {:else}
                    <div class="col-span-2 py-12 text-center border border-dashed border-white/10 rounded-2xl">
                        <p class="text-xs text-slate-600 animate-pulse uppercase tracking-widest font-bold">Waiting for strategy data...</p>
                    </div>
                {/each}
            </div>
        </section>

        <!-- Sidebar: Controls & Feed -->
        <div class="space-y-6">
            <section class="card bg-slate-900/50 p-6 rounded-2xl border border-white/5">
                <h2 class="text-[10px] font-black uppercase text-slate-500 tracking-[0.2em] mb-4">Operations</h2>
                <button 
                    onclick={triggerBacktest}
                    class="w-full py-3 bg-amber-500 text-slate-950 font-black rounded-xl uppercase text-xs hover:bg-amber-400 transition-all shadow-lg shadow-amber-500/10"
                >
                    Run Local Backtest
                </button>
            </section>

            <section class="card bg-slate-900/50 p-6 rounded-2xl border border-white/5 flex flex-col h-64">
                <h2 class="text-[10px] font-black uppercase text-slate-500 tracking-[0.2em] mb-4">Fabric Live Feed</h2>
                <div class="space-y-2 flex-1 overflow-y-auto no-scrollbar font-mono text-[10px]">
                    {#each prices as tick}
                        <div class="flex justify-between border-b border-white/5 py-1">
                            <span class="text-slate-500">{tick.ticker || 'TICK'}</span>
                            <span class="text-emerald-500">${tick.value}</span>
                        </div>
                    {/each}
                </div>
            </section>
        </div>
    </div>

    {#if lastSignal}
        <div class="fixed bottom-6 right-6 p-4 bg-indigo-500 text-slate-950 rounded-2xl shadow-2xl font-black uppercase text-[10px] tracking-widest animate-bounce border-4 border-slate-950">
            System Alert: {lastSignal}
        </div>
    {/if}
</main>

<style>
    .no-scrollbar::-webkit-scrollbar { display: none; }
</style>

// 3_service_templates/react_base/src/App.jsx
import React, { useState, useEffect } from 'react';
import { fabric } from '../../_shared/utils/fabric-client.ts';

export default function App({ context }) {
    const [items] = useState(context.data.items || []);
    const [isConnected, setIsConnected] = useState(false);
    const [latestEvent, setLatestEvent] = useState(null);
    const themeColor = context.state.theme_color || 'indigo';

    useEffect(() => {
        // Initialize Fabric Gateway connection
        fabric.connect();
        
        // Listen for real-time events
        const unsubscribe = fabric.onEvent((event) => {
            setLatestEvent(event);
            setIsConnected(true);
            
            // Auto-refresh logic if global sync is requested
            if (event.event === 'data_sync' || event.event === `${context.slug}_updated`) {
                handleTestSync();
            }
        });

        return () => unsubscribe();
    }, [context.slug]);

    const handleTestSync = async () => {
        try {
            // Using Fabric SDK call for orchestrated routing
            const data = await fabric.call(`/app/core/${context.slug}/api/sync`, {
                method: 'POST',
                body: JSON.stringify({ ping: 'pong', slug: context.slug })
            });
            console.log("Fabric Sync Success:", data);
        } catch (e) {
            console.error("Fabric Sync failed", e);
        }
    };

    return (
        <div className="p-8 min-h-screen bg-slate-50 text-slate-900 font-sans">
            
            {/* Fabric Gateway Status Bar */}
            <div className={`mb-6 flex items-center justify-between px-4 py-2 rounded-xl border text-[10px] font-bold uppercase tracking-widest transition-all ${isConnected ? 'bg-emerald-50 border-emerald-100 text-emerald-600' : 'bg-rose-50 border-rose-100 text-rose-600'}`}>
                <div className="flex items-center gap-2">
                    <span className={`relative flex h-2 w-2 ${isConnected ? 'animate-pulse' : ''}`}>
                        <span className={`inline-flex rounded-full h-2 w-2 ${isConnected ? 'bg-emerald-500' : 'bg-rose-500'}`}></span>
                    </span>
                    <span>{isConnected ? 'Fabric Gateway: Active' : 'Fabric Gateway: Connecting...'}</span>
                </div>
                
                {latestEvent && (
                    <div className="truncate max-w-xs opacity-60">
                        Event: {latestEvent.event}
                    </div>
                )}
            </div>

            <header className={`mb-10 border-b-4 border-${themeColor}-500 pb-6 flex justify-between items-center`}>
                <div>
                    <h1 className="text-4xl font-black tracking-tighter uppercase">{context.name}</h1>
                    <div className="flex items-center gap-3 mt-1">
                        <span className="text-xs font-mono text-slate-400">SHARD: {context.slug}</span>
                        <button 
                            onClick={() => fabric.broadcast(`${context.slug}_ping`, { timestamp: new Date() })}
                            className="text-[9px] text-blue-500 hover:underline font-bold"
                        >
                            [ Broadcast Pulse ]
                        </button>
                    </div>
                </div>
                <button 
                    onClick={handleTestSync}
                    className={`px-6 py-2 bg-${themeColor}-600 text-white rounded-full font-bold text-xs uppercase tracking-widest hover:shadow-lg transition-all active:scale-95`}
                >
                    Sync Node
                </button>
            </header>

            <main className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <section className="bg-white p-6 rounded-3xl shadow-sm border border-slate-200">
                    <h2 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.2em] mb-4">Initial DNA</h2>
                    <pre className="text-[11px] bg-slate-950 text-emerald-400 p-4 rounded-xl overflow-x-auto">
                        {JSON.stringify(context.state, null, 2)}
                    </pre>
                </section>

                <section className="bg-white p-6 rounded-3xl shadow-sm border border-slate-200">
                    <h2 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.2em] mb-4">Live Memory (app_data)</h2>
                    <div className="space-y-3">
                        {items.length > 0 ? items.map((item, i) => (
                            <div key={i} className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex justify-between group hover:border-blue-200 transition-colors">
                                <span className="font-bold">{item.label}</span>
                                <span className="text-slate-400 text-xs">ID: {item.id}</span>
                            </div>
                        )) : (
                            <div className="py-10 text-center border-2 border-dashed rounded-2xl text-slate-300 italic">
                                No records found in memory.
                            </div>
                        )}
                    </div>
                </section>
            </main>
        </div>
    );
}
